### ISSUE TITLE
Server on web?

### ISSUE THREAD

**Issue by MovingGifts** [react-native-training/create-xp-app#14]
Is there a way to serve the web app on a server like `localhost:3000` out of the box or do we have to manually set one up?

So far, I have been using the `file:///...index.html` but with routing involved, thought I'd check first :)

**Comment by dabit3** [comment]
Right now we don't have it set up to run on a server out of the box. The simplest way would be to do something like python-simple-httpserver or something, but it would be simple to create a node server if you would like to submit a pr :)

**Comment by MovingGifts** [comment]
Thank you for your reply :)

I got it working using `browser-sync-webpack-plugin` following [this](https://github.com/Microsoft/reactxp/issues/172) ReactXP thread. It automatically refreshes on changes to code as well :)

**Comment by dabit3** [comment]
Awesome, thanks for updating this issue and closing it :) Sorry I could not be of more help!

**Comment by MovingGifts** [comment]
Sure thing! No worries @dabit3, you're of great help to the community :)
