### ISSUE TITLE
npm start doesn't do anything

### ISSUE THREAD

**Issue by QuantumInformation** [react-native-training/create-xp-app#17]
I was expecting it to open up a simulator like in RN projects. (run ios)

It just sticks on 

![image](https://user-images.githubusercontent.com/216566/28239475-d927cf5a-6964-11e7-9f09-d7aa5f6feba2.png)
I'm running `npm run rn-watch` too

**Comment by dabit3** [comment]
Have you tried `react-native run-ios`?

**Comment by dabit3** [comment]
This seems to be working, if you are still having issues, please let me know.
