### ISSUE TITLE
Is there a webpack dev server watch?

### ISSUE THREAD

**Issue by adamchenwei** [react-native-training/create-xp-app#3]
Basically I wonder if you have a hot-loading already in place, so we dont have to save + reload all the time?

**Comment by dabit3** [comment]
@adamchenwei not right now, but this would be a great thing to add. Are you saying for the web?

**Comment by nikolasleblanc** [comment]
https://github.com/react-native-training/create-xp-app/pull/8

**Comment by adamchenwei** [comment]
awesome!!!!
