### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by QuantumInformation** [react-native-training/create-xp-app#5]
Are you somehow cloning the https://github.com/Microsoft/reactxp project and doing some modifications?

**Comment by dabit3** [comment]
Exactly. Right now we are actually cloning https://github.com/react-native-training/reactxp-starter . Would like to add some more features in the future though..

**Comment by dabit3** [comment]
Updated to now use local file path that is part of the project!

**Comment by QuantumInformation** [comment]
Is there any overlap with this and create react native app?
