### ISSUE TITLE
Don’t use `new` as a program name

### ISSUE THREAD

**Issue by Haroenv** [react-native-training/create-xp-app#6]
It would be nice to get this working with `yarn create`, which simply passes down the arguments after installing. Now we have to do `yarn create xp-app new my-app`, while `yarn create xp-app my-app` would be more obvious.

This is blocked by #4

**Comment by dabit3** [comment]
@Haroenv working on this. Version 0.3.0 now does not need the new command. Now I'm adding the new npm repo for xp-app which would allow this. Will update when Is working!

**Comment by dabit3** [comment]
Ok, this should be working. Let me know if you have any issues @Haroenv thanks!

**Comment by Haroenv** [comment]
That’s right, it works!
